test_asr:
  description: "测试语音识别服务"
  fields:
    service_name:
      description: "语音识别服务名称"
      example: "DoubaoASR"
      required: true
      selector:
        text:
    text:
      description: "要测试的文本"
      example: "测试语音识别"
      selector:
        text: 